#### 문제 설명
트럭 여러 대가 강을 가로지르는 일차선 다리를 정해진 순으로 건너려 합니다. 모든 트럭이 다리를 건너려면 최소 몇 초가 걸리는지 알아내야 합니다. 다리에는 트럭이 최대 bridge_length대 올라갈 수 있으며, 다리는 weight 이하까지의 무게를 견딜 수 있습니다. 단, 다리에 완전히 오르지 않은 트럭의 무게는 무시합니다.

예를 들어, 트럭 2대가 올라갈 수 있고 무게를 10kg까지 견디는 다리가 있습니다. 무게가 [7, 4, 5, 6]kg인 트럭이 순서대로 최단 시간 안에 다리를 건너려면 다음과 같이 건너야 합니다.

경과 시간	다리를 지난 트럭	다리를 건너는 트럭	대기 트럭

0	[]	[]	[7,4,5,6]

1~2	[]	[7]	[4,5,6]

3	[7]	[4]	[5,6]

4	[7]	[4,5]	[6]

5	[7,4]	[5]	[6]

6~7	[7,4,5]	[6]	[]

8	[7,4,5,6]	[]	[]

따라서, 모든 트럭이 다리를 지나려면 최소 8초가 걸립니다.

solution 함수의 매개변수로 다리에 올라갈 수 있는 트럭 수 bridge_length, 다리가 견딜 수 있는 무게 weight, 트럭 별 무게 truck_weights가 주어집니다. 이때 모든 트럭이 다리를 건너려면 최소 몇 초가 걸리는지 return 하도록 solution 함수를 완성하세요.

#### 제한 조건
bridge_length는 1 이상 10,000 이하입니다.
weight는 1 이상 10,000 이하입니다.
truck_weights의 길이는 1 이상 10,000 이하입니다.
모든 트럭의 무게는 1 이상 weight 이하입니다.

#### 입출력 예
bridge_length	weight	truck_weights	return

2	10	[7,4,5,6]	8

100	100	[10]	101

100	100	[10,10,10,10,10,10,10,10,10,10]	110

In [22]:
bridge_lengthes = [2, 100, 100]
weights = [10, 100, 100]
truck_weights_list = [
    [7,4,5,6],
    [10],
    [10,10,10,10,10,10,10,10,10,10]
]

In [23]:
import numpy as np

In [24]:
def solution(bridge_length, weight, truck_weights):
    pass_truck = list()
    pass_times = np.array([])
    time = 1
    while len(truck_weights) != 0 or len(pass_truck) != 0:
        time += 1
        pass_weight = sum(pass_truck)
        if len(truck_weights) > 0 and pass_weight + truck_weights[0] <= weight:
            truck = truck_weights.pop(0)
            pass_truck.append(truck)
            pass_times = np.append(pass_times, 0)
        pass_times += 1
        pass_weight += truck
        if len(pass_times[pass_times >= bridge_length]) != 0:
            pass_truck.pop(0)
            pass_times = pass_times[1:]
    return time
            

In [25]:
for bridge_length, weight, truck_weights in zip(bridge_lengthes, weights, truck_weights_list):
    print(solution(bridge_length, weight, truck_weights))

a
b
[1.]
a
[2.]
a
b
[1.]
a
b
[2. 1.]
a
[2.]
a
b
[1.]
a
[2.]
8
a
b
[1.]
a
[2.]
a
[3.]
a
[4.]
a
[5.]
a
[6.]
a
[7.]
a
[8.]
a
[9.]
a
[10.]
a
[11.]
a
[12.]
a
[13.]
a
[14.]
a
[15.]
a
[16.]
a
[17.]
a
[18.]
a
[19.]
a
[20.]
a
[21.]
a
[22.]
a
[23.]
a
[24.]
a
[25.]
a
[26.]
a
[27.]
a
[28.]
a
[29.]
a
[30.]
a
[31.]
a
[32.]
a
[33.]
a
[34.]
a
[35.]
a
[36.]
a
[37.]
a
[38.]
a
[39.]
a
[40.]
a
[41.]
a
[42.]
a
[43.]
a
[44.]
a
[45.]
a
[46.]
a
[47.]
a
[48.]
a
[49.]
a
[50.]
a
[51.]
a
[52.]
a
[53.]
a
[54.]
a
[55.]
a
[56.]
a
[57.]
a
[58.]
a
[59.]
a
[60.]
a
[61.]
a
[62.]
a
[63.]
a
[64.]
a
[65.]
a
[66.]
a
[67.]
a
[68.]
a
[69.]
a
[70.]
a
[71.]
a
[72.]
a
[73.]
a
[74.]
a
[75.]
a
[76.]
a
[77.]
a
[78.]
a
[79.]
a
[80.]
a
[81.]
a
[82.]
a
[83.]
a
[84.]
a
[85.]
a
[86.]
a
[87.]
a
[88.]
a
[89.]
a
[90.]
a
[91.]
a
[92.]
a
[93.]
a
[94.]
a
[95.]
a
[96.]
a
[97.]
a
[98.]
a
[99.]
a
[100.]
101
a
b
[1.]
a
b
[2. 1.]
a
b
[3. 2. 1.]
a
b
[4. 3. 2. 1.]
a
b
[5. 4. 3. 2. 1.]
a
b
[6. 5. 4. 3. 2. 1.]
a
b
[7. 6. 5. 4. 3. 2. 1.]
a
b
[8. 7. 6. 